FROM ubuntu:20.04
    MAINTAINER Healthverity Audience Manager <audience-manager-support@healthverity.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y gnupg gzip dos2unix && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify GNUPG and gzip installation
RUN gpg --version && gzip --version
